# Generated by Django 5.2.10 on 2026-01-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0002_alter_hotel_address_alter_hotel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='google_map_url',
            field=models.URLField(blank=True, help_text='Google Maps location link', max_length=500, null=True),
        ),
    ]
