# Generated by Django 5.2.10 on 2026-01-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_attraction_address_alter_attraction_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalartifact',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL for image (optional)'),
        ),
        migrations.AlterField(
            model_name='digitalartifact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artifacts/'),
        ),
    ]
