# Generated by Django 5.2.10 on 2026-01-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_digitalartifact_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
