# Generated by Django 5.2.10 on 2026-01-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='linkedin_url',
            new_name='profile_url',
        ),
    ]
