# Generated by Django 5.2.10 on 2026-01-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_teammember_photo_url_alter_teammember_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='اللواء أ.ح / محمد سالمان الزملوط', max_length=200)),
                ('title', models.CharField(default='محافظ الوادي الجديد', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='governor_photos/')),
                ('welcome_heading', models.CharField(default='كلمة السيد المحافظ', max_length=200)),
                ('welcome_message', models.TextField(default='يسعدني ويشرفني أن أكون بين أهلي في محافظة الوادي الجديد فالمواطن أول اهتماماتي وأقسمت اليمين لأرعى مصالحه وأن أحافظ عليه. أما تعظيم الموارد المتاحة بالمحافظة وترشيد الاستهلاك والتواصل بين جميع الجهات الإدارية لتوفير الكثير من الجهد والوقت وضرورة حسن معاملة المواطنين والعمل بروح الفريق والالتزام الكامل بتوفير الخدمات من أساسيات العمل بالمحافظة.')),
                ('career_highlights', models.TextField(default='تاريخ التخرج: الكلية الحربية 1/4/1980.\nتولى الوظائف القيادية في سلاح المشاة حتى قائد الفرقة 16 مشاة.\nمساعد قائد المنطقة الشمالية العسكرية.\nرئيس أركان الجيش الثاني الميداني.\nرئيس أركان المنطقة المركزية العسكرية.\nقائد المنطقة الشمالية العسكرية.\nرئيس هيئة البحوث العسكرية.\nالأوسمة: ميدالية الخدمة الطويلة، نوط الواجب العسكري، نوط الخدمة الممتازة.')),
            ],
        ),
    ]
